global using DevKit.ExecutionEngine.Oracle.Abstractions;
global using DevKit.ExecutionEngine.Oracle.Settings;
global using DevKit.Extensions;
global using Microsoft.Extensions.Options;
global using Oracle.ManagedDataAccess.Client;
global using System;
global using System.Data;
global using System.Data.Common;
global using System.Reflection;
