<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net48;netstandard2.0;net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<OutputType>Library</OutputType>
		<Company>David Vázquez Palestino</Company>
		<Product>CoreUtilerias</Product>
		<AssemblyVersion>2025.08.13</AssemblyVersion>
		<FileVersion>2025.08.13</FileVersion>
		<Version>2025.08.13</Version>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
		<Title>CoreUtilerias - Biblioteca de Extensiones para .NET</Title>
		<Authors>David Vázquez Palestino</Authors>
		<PackageId>CoreUtilerias</PackageId>
		<Description>CoreUtilerias es una biblioteca de extensiones que proporciona métodos optimizados para el manejo de DataTable, DataRow e IDataReader en .NET. Incluye funcionalidades avanzadas para la manipulación de datos, conversión de tipos y operaciones de ADO.NET. Compatible con múltiples versiones de .NET (4.8, 6.0, 7.0, 8.0 y 9.0), lo que la convierte en una herramienta esencial para desarrolladores que necesitan mejorar la productividad en el manejo de datos.</Description>
		<Copyright>Copyright  David Vázquez Palestino</Copyright>
		<PackageOutputPath>C:\Github\Packages\CoreUtilerias</PackageOutputPath>
		<PackageIcon>102042_tools_icon.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
		<PackageReference Include="System.Text.Json" Version="9.0.8" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Imagenes\102042_tools_icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>

		<None Update="Imagenes\102042_tools_icon.png">
			<PackagePath>\</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<Pack>True</Pack>
		</None>

	</ItemGroup>

	<ItemGroup>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Update="README.md">
			<Pack>True</Pack>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Include="LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Update="LICENSE">
			<Pack>True</Pack>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Include="Imagenes\102042_tools_icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>

		<None Update="Imagenes\102042_tools_icon.png">
			<PackagePath>\</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<Pack>True</Pack>
		</None>

	</ItemGroup>

	<ItemGroup>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Update="README.md">
			<Pack>True</Pack>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Include="LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Update="LICENSE">
			<Pack>True</Pack>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>


</Project>