<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net48;net8.0;net9.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<PackageId>CoreMailKit</PackageId>
		<Title>CoreMailKit - Biblioteca de Gestión de Correo Electrónico</Title>
		
		<Authors>David Vázquez Palestino</Authors>
		<Company>David Vázquez Palestino</Company>
		<Product>CoreMailKit</Product>
		<Description>CoreMailKit es una biblioteca completa para el manejo de correos electrónicos en aplicaciones .NET. Proporciona funcionalidades avanzadas para la creación, envío y recepción de emails, incluyendo soporte para adjuntos, HTML, múltiples destinatarios, configuración SMTP personalizada y manejo de errores. Compatible con múltiples versiones de .NET (4.8, 8.0 y 9.0) y utiliza MailKit para la implementación eficiente de protocolos de correo electrónico.</Description>
		<Copyright>Copyright David Vázquez Palestino</Copyright>

		<AssemblyVersion>2025.10.26</AssemblyVersion>
		<Version>2025.10.26</Version>
		<FileVersion>2025.10.26</FileVersion>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
		<AssemblyName>CoreMailKit</AssemblyName>
		<RootNamespace>CoreMailKit</RootNamespace>
		<PackageOutputPath>C:\Github\Packages\CoreMailKit</PackageOutputPath>
		<PackageIcon>102042_tools_icon.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<None Include="Imagenes\102042_tools_icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<Optimize>true</Optimize>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MailKit" Version="4.14.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.10" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Imagenes\102042_tools_icon.png">
	    <PackagePath>\</PackagePath>
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	    <Pack>True</Pack>
	  </None>
	 
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Update="README.md">
			<Pack>True</Pack>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Include="LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Update="LICENSE">
			<Pack>True</Pack>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
