<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0-windows;net9.0-windows;net10.0-windows;</TargetFrameworks>
		<OutputType>Library</OutputType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<UseWindowsForms>true</UseWindowsForms>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageId>CoreMessageBox</PackageId>
		<Title>CoreMessageBox - Biblioteca de Mensajes Personalizados para Windows Forms</Title>
		<Authors>David Vázquez Palestino</Authors>
		<Company>David Vázquez Palestino</Company>
		<Product>CoreMessage</Product>
		<Description>CoreMessageBox es una biblioteca que proporciona componentes y métodos optimizados para mostrar mensajes personalizados en aplicaciones Windows Forms. Incluye extensiones para MessageBox, cuadros de diálogo personalizados y notificaciones. Compatible con .NET Framework 4.8 y proporciona una interfaz de usuario moderna y consistente para la comunicación con los usuarios.</Description>
		<Version>2026.03.06</Version>
		<AssemblyVersion>2026.03.06</AssemblyVersion>
		<FileVersion>2026.03.06</FileVersion>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
		<Copyright>Copyright  David Vázquez Palestino</Copyright>
		<PackageOutputPath>C:\Github\Packages\CoreMessageBox</PackageOutputPath>
		<PackageIcon>102042_tools_icon.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<None Include="Imagenes\102042_tools_icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<DebugType>none</DebugType>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
		<OutputPath>bin\x64\Debug\</OutputPath>
		<LangVersion>10</LangVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
		<OutputPath>bin\x64\Release\</OutputPath>
		<LangVersion>10</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
		<PackageReference Include="Microsoft.Windows.Compatibility" Version="10.0.5" />
		<PackageReference Include="Serilog" Version="4.3.1" />
	</ItemGroup>
	
	<ItemGroup>
	  <None Update="Imagenes\102042_tools_icon.png">
	    <PackagePath>\</PackagePath>
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	    <Pack>True</Pack>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Update="README.md">
			<Pack>True</Pack>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Include="LICENSE">
			<Pack>True</Pack>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Update="LICENSE">
			<Pack>True</Pack>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>